# Generated by Django 5.1.6 on 2025-02-20 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_ticket_image_ticket_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='photo',
            new_name='image',
        ),
    ]
