# Generated by Django 5.1.6 on 2025-03-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_userfollows_userfollow'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfollow',
            name='blocked_follower',
            field=models.BooleanField(default=False),
        ),
    ]
